server:
  port: ${SERVER_PORT:10001}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/v2/core}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:core-service}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://mariadb:3306/miarma_v2}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  jackson:
    default-property-inclusion: non_null
    time-zone: Europe/Madrid

jwt:
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}
  private-key-path: ${JWT_PRIVATE_KEY_PATH}
  public-key-path: ${JWT_PUBLIC_KEY_PATH}

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

filesDir: ${FILES_DIR:/files}

management:
  endpoints:
    web:
      exposure:
        include: health,info

backlib:
  upload:
    path: ${MINECRAFT_UPLOAD_PATH}

core:
  url: ${CORE_URL}

minecraft:
  user: ${MINECRAFT_USER}
  password: ${MINECRAFT_PASS}

discord:
  url: ${DISCORD_URL}